"These values are set for vundle settings
"set nocompatible " explicitly get out of vi-compatible mode
filetype off	" required

syntax on "turn on color syntax highlighting 

"==============PATHOGEN============"
" Use pathogen to easily modify the runtime path to include all
" plugins under the ~/.vim/bundle directory
execute pathogen#infect()
"syntax on
"filetype plugin indent on 
"==========PATHOGEN END============"


"==============VUNDLE==============="
"vundle: set the runtime path to include vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'saltstack/salt-vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " load filetype plugins/indent settings
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"==============VUNDLE END===================

" Vim UI {
	colorscheme solarized
	set background=dark
        set statusline=%F%m%r%h%w\ [Lines:%L]\ [Type:%{&ff}]\ %y\ [%p%%]\ [%04l,%04v]\ [FoldLevel:%{foldlevel('.')}]
        "              | | | | |          |          |        |    |       |    |                 |
        "              | | | | |          |          |        |    |       |    |                 + current foldlevel
        "              | | | | |          |          |        |    |       |    + current column
        "              | | | | |          |          |        |    |       +-- current line
        "              | | | | |          |          |        |    +-- current % into file
        "              | | | | |          |          |        +-- current syntax in square brackets 
        "              | | | | |          |          +-- current fileformat
        "              | | | | |          +-- number of lines
        "              | | | | +-- preview flag in square brackets
        "              | | | +-- help flag in square brackets
        "              | | +-- readonly flag in square brackets
        "              | +-- rodified flag in square brackets
        "              +-- full path to file in the buffer

"}

" Vim FUNC {
	set number
" }


" StatusLine {
  " http://stackoverflow.com/questions/5375240/a-more-useful-statusline-in-vim
  set statusline=
  set statusline+=%7*\[%n]                                  "buffernr
  set statusline+=%1*\ %<%F\                                "File+path
  set statusline+=%2*\ %y\                                  "FileType
  set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
  set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
  set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..) 
  set statusline+=%5*\ %{&spelllang}\%{HighlightSearch()}\  "Spellanguage & Highlight on?
  set statusline+=%8*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
  set statusline+=%9*\ col:%03c\                            "Colnr
  set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.

  function! HighlightSearch()
    if &hls
      return 'H'
    else
      return ''
    endif
  endfunction

  hi User1 guifg=#ffdad8  guibg=#880c0e
  hi User2 guifg=#000000  guibg=#F4905C
  hi User3 guifg=#292b00  guibg=#f4f597
  hi User4 guifg=#112605  guibg=#aefe7B
  hi User5 guifg=#051d00  guibg=#7dcc7d
  hi User7 guifg=#ffffff  guibg=#880c0e gui=bold
  hi User8 guifg=#ffffff  guibg=#5b7fbb
  hi User9 guifg=#ffffff  guibg=#810085
  hi User0 guifg=#ffffff  guibg=#094afe

" }
"
"Key mappings / bindings {
	cmap w!! w !sudo tee % >/dev/null " incase you forget to sudo a file when saving - just type "w!!"
"}
